baseURL = "https://shenchingtou.github.io/asian-founders-archive/"
languageCode = "en-us"
title = "Asian Founders Archives"
description = "An archive of product and business development experiences from startup founders in East Asia. Formerly Business 3.0"
theme = "book"

publishDir = "docs"
googleAnalytics = "UA-117941752-1"

