baseURL = "http://example.org/"
languageCode = "en-us"
title = "Business 3.0"
description = "An archive of product and business development experiences from startup founders in East Asia"
theme = "book"

